<a href="https://colab.research.google.com/github/shafat0/Road-for-Data-Scientist/blob/main/SALES_DATASET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hii, This is my first basic project for Clean and Summarize a messy sales dataset using pandas

In [15]:
# Let's import the Libraries first.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
# Now let's mount the drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# SETP 1:-  Let's load the data using "pd.read_csv()" function.

In [18]:
# Let's load the data using "pd.read_csv()" function.
sales = pd.read_csv('/content/drive/MyDrive/SALES_DATA.csv')
sales

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New
...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning

In [21]:
print("Original Data:")
print(sales.head(10))
print("\nInfo:")
print(sales.info())

Original Data:
   Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
0        1052  2023-02-03       Bob  North       5053.97             18
1        1093  2023-04-21       Bob   West       4384.02             17
2        1015  2023-09-21     David  South       4631.23             30
3        1072  2023-08-24       Bob  South       2167.94             39
4        1061  2023-03-24   Charlie   East       3750.20             13
5        1021  2023-02-11   Charlie   West       3761.15             32
6        1083  2023-04-11       Bob   West        618.31             29
7        1087  2023-01-06       Eve  South       7698.92             46
8        1075  2023-06-29     David  South       4223.39             30
9        1075  2023-10-09   Charlie   West       8239.58             18

  Product_Category  Unit_Cost  Unit_Price Customer_Type
0        Furniture     152.75      267.22     Returning
1        Furniture    3816.39     4209.44     Returning
2             Food     261.56      371.40     Returning
3         Clothing    4330.03     4467.75           New
4      Electronics     637.37      692.71           New
5             Food     900.79     1106.51           New
6        Furniture    2408.81     2624.09     Returning
7        Furniture    3702.51     3964.65           New
8        Furniture     738.06     1095.45           New
9         Clothing    2228.35     2682.34           New

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_ID        1000 non-null   int64
 1   Sale_Date         1000 non-null   object
 2   Sales_Rep         1000 non-null   object
 3   Region            1000 non-null   object
 4   Sales_Amount      1000 non-null   float64
 5   Quantity_Sold     1000 non-null   int64
 6   Product_Category  1000 non-null   object
 7   Unit_Cost         1000 non-null   float64
 8   Unit_Price        1000 non-null   float64
 9   Customer_Type     1000 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 78.3+ KB
None

# SETP 2:- Detect missing values using "df.isull().sum()" function.

In [25]:
sales.isnull()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

In [26]:
sales.isnull().sum()

Product_ID          0
Sale_Date           0
Sales_Rep           0
Region              0
Sales_Amount        0
Quantity_Sold       0
Product_Category    0
Unit_Cost           0
Unit_Price          0
Customer_Type       0
dtype: int64

# STEP 3:- Now we will Replace all missing values in numeric columns with the mean of that column.

In [29]:
# Handling numeric missing values
sales.fillna(sales.mean(numeric_only=True), inplace=True)

In [30]:
# Handling categorical values
sales.fillna("unknown",inplace = True)

In [31]:
sales

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New
...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning

# Remove Duplicates:-

In [32]:
sales.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [33]:
sales.duplicated().sum()

np.int64(0)

In [34]:
sales.drop_duplicates(inplace=True)

In [35]:
sales

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New
...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning

# SETP 5:-Rename columns to lowercase and replace spaces with underscores.

In [36]:
sales.columns = [col.lower().replace(' ','_') for col in sales.columns]

In [37]:
print('\n Columns after renaming:-')
print(sales.columns)

 Columns after renaming:-
Index(['product_id', 'sale_date', 'sales_rep', 'region', 'sales_amount',
       'quantity_sold', 'product_category', 'unit_cost', 'unit_price',
       'customer_type'],
      dtype='object')

# STEP 6:- Summarize the cleaned data:-

In [38]:
print('\n Summary statistics:-')
print(sales.describe())

 Summary statistics:-
        product_id  sales_amount  quantity_sold    unit_cost   unit_price
count  1000.000000   1000.000000    1000.000000  1000.000000  1000.000000
mean   1050.128000   5019.265230      25.355000  2475.304550  2728.440120
std      29.573505   2846.790126      14.159006  1417.872546  1419.399839
min    1001.000000    100.120000       1.000000    60.280000   167.120000
25%    1024.000000   2550.297500      13.000000  1238.380000  1509.085000
50%    1051.000000   5019.300000      25.000000  2467.235000  2696.400000
75%    1075.000000   7507.445000      38.000000  3702.865000  3957.970000
max    1100.000000   9989.040000      49.000000  4995.300000  5442.150000

In [40]:
sales

,product_id,sale_date,sales_rep,region,sales_amount,quantity_sold,product_category,unit_cost,unit_price,customer_type
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New
...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning

In [41]:
print('\n Total quantity  and average per region:-')
region_summary = sales.groupby('region').agg({'quantity_sold':'sum','unit_price':'mean'})
print(region_summary)

 Total quantity  and average per region:-
        quantity_sold   unit_price
region
East             6356  2736.433460
North            6705  2709.393483
South            5808  2703.611593
West             6486  2763.663279

In [44]:
print('\n Top 3 products by quantity sold:')
product_summary = sales.groupby('product_id')['quantity_sold'].sum().sort_values(ascending=False).head(3)
print(product_summary)

 Top 3 products by quantity sold:
product_id
1090    590
1092    548
1062    506
Name: quantity_sold, dtype: int64

In [47]:
# BONUS = Create total_sale column
sales['total_sale']=sales['quantity_sold']*sales['unit_price']
sales

,product_id,sale_date,sales_rep,region,sales_amount,quantity_sold,product_category,unit_cost,unit_price,customer_type,total_sale
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,4809.96
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,71560.48
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,11142.00
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,174242.25
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,9005.23
...,...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,21768.60
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,68686.80
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,7450.59
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,145992.21
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,140480.64

In [52]:
# Here we will check the data with highest total sales:
print('\n Date with highest total sales:')
date_sales = sales.groupby('sale_date')['total_sale'].sum()
print(date_sales.sort_values(ascending=False).head(1))

 Date with highest total sales:
sale_date
2023-10-15    895505.16
Name: total_sale, dtype: float64

#Now, let's save the cleaned data to Google Drive.

In [56]:
sales.to_csv('/content/drive/MyDrive/sales_data_cleaned_drive.csv', index=False)
print('Cleaned sales data saved to Google Drive as sales_data_cleaned_drive.csv')

Cleaned sales data saved to Google Drive as sales_data_cleaned_drive.csv